modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU LGPL 3.0"

[[mods]]
modId = "millennium"
version = "${file.jarVersion}"
displayName = "Millennium"
#logoFile="millennium.png" #optional
credits="glTF loader mod author TimLee9024"
authors = "DustW"
description = '''

'''

[[dependencies.millennium]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.millennium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[mods]]
modId="mcgltf"
version="${file.jarVersion}"
displayName="MCglTF"
updateJSONURL="https://raw.githubusercontent.com/TimLee9024/MCglTF/1.18.2-Forge/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mcgltf/"
logoFile="examplemod.png"
credits="Marco Hutter (javagl), for making JglTF and jMonkeyEngine 3 team, for making MikkTSpace generator."
authors="TimLee9024"
description='''
A glTF model loader library based on JglTF for Minecraft.
'''

[[dependencies.mcgltf]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcgltf]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"